### ISSUE TITLE
Variant.cs(12,14): error CS1031: Type expected

### ISSUE THREAD

**Issue by ArsenShnurkov** [macias/NaiveLanguageTools#1]
This error occurs in the <a href="https://github.com/macias/NaiveLanguageTools/blob/025310e2c07e5b00c4dadd342e159515972ec79a/NaiveLanguageTools.Common/Variant.cs#L12">line 12 of Variant.cs</a>

the full log of build is here, but no much details in it
https://gist.githubusercontent.com/ArsenShnurkov/777c7b96ee14c18bbf54a77b675d1e7e/raw/916fa3d16d0673393b8a007de02b36c7aa31ee79/gistfile1.txt

UPD: removing comma between "where"s fixes this bug

**Comment by macias** [comment]
Thank you for the report and sorry for this, fixed.
